# Generated by Django 4.0.3 on 2022-04-18 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supports', '0002_faq_writer_alter_faq_content_alter_faq_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='writer',
            new_name='creator',
        ),
    ]
